# Generated by Django 4.2.16 on 2024-10-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localvotacao",
            name="eleitores",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
