# Generated by Django 4.2.16 on 2024-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localvotacao",
            name="falta_militar",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="localvotacao",
            name="eleitores",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
