# Generated by Django 4.2.16 on 2024-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_localvotacao_local_votacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localvotacao",
            name="status_fiscalizacao",
            field=models.CharField(
                choices=[
                    ("Fiscalizado", "Fiscalizado"),
                    ("Não Fiscalizado", "Não Fiscalizado"),
                ],
                default="Não Fiscalizado",
                max_length=20,
            ),
        ),
    ]
