# Generated by Django 4.2.16 on 2024-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_localvotacao_opm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_ocorrencia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código da Ocorrência"
                    ),
                ),
                (
                    "quantidade_conduzidos",
                    models.IntegerField(verbose_name="Quantidade de Conduzidos"),
                ),
                ("opm", models.CharField(max_length=100, verbose_name="OPM")),
            ],
        ),
    ]
