# Generated by Django 4.2.16 on 2024-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(default="", max_length=100, verbose_name="Tipo"),
        ),
    ]
