# Generated by Django 4.2.16 on 2024-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ocorrencia_tipo"),
    ]

    operations = [

        migrations.AlterField(
            model_name="localvotacao",
            name="opm",
            field=models.CharField(
                choices=[
                    ("1º BPM", "1º BPM"),
                    ("5º BPM", "5º BPM"),
                    ("BEPTUR", "BEPTUR"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="opm",
            field=models.CharField(
                choices=[
                    ("1º BPM", "1º BPM"),
                    ("5º BPM", "5º BPM"),
                    ("BEPTUR", "BEPTUR"),
                ],
                max_length=100,
                verbose_name="OPM",
            ),
        ),
    ]
