# Generated by Django 4.2.16 on 2024-10-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_localvotacao_cia_alter_localvotacao_opm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localvotacao",
            name="cia",
        ),
    ]
